/**
 * Watercolour artwork (PNGs with transparent backgrounds) in /public/florals. The bouquet and the spray are from a
 * Freepik watercolour set Sibin supplied on 2026-10-02 (credited in the README); the rest is Sibin's own or generated
 * from the spec's prompt, with the white keyed out.
 */
export interface FloralArt {
  src: string;
  width: number;
  height: number;
}

/** A mint spray: blooms at the top-left, foliage trailing down to the right. */
export const spray: FloralArt = { src: "/florals/spray.png", width: 365, height: 444 };

/** A round bouquet of mint and cream roses with white anemones. */
export const bouquet: FloralArt = { src: "/florals/bouquet.png", width: 441, height: 445 };

/** Teal wax seal with the couple's script monogram (generated by Sibin from the prompt in the spec, 2026-10-02). */
export const sealArt: FloralArt = { src: "/florals/seal.png", width: 1024, height: 1024 };
/** The rings with blossoms, laid beside the couple's photograph (Sibin's own; background keyed out). */
export const rings: FloralArt = { src: "/florals/rings.png", width: 497, height: 384 };
/** The couple painted in watercolour among eucalyptus and dried stems, for the celebration (Sibin supplied it on 2026-10-04; white background keyed out). */
export const ceremony: FloralArt = { src: "/florals/ceremony.png", width: 718, height: 730 };
/** The couple's clasped hands in watercolour, for guests who join from afar (Sibin supplied it on 2026-10-04; the white lifted out so the grey wash stays translucent). */
export const hands: FloralArt = { src: "/florals/hands.png", width: 806, height: 1000 };
