// AUTO-GENERATED by scripts/photos.mjs — do not edit by hand.
import type { Photo } from "./types";

export const photos: { hero: Photo; heroScene: Photo } = {
  "hero": {
    "src": "/photos/hero.jpg",
    "width": 832,
    "height": 1248,
    "alt": {
      "en": "Priyank and Tosmy",
      "ml": "പ്രിയങ്കും ടോസ്മിയും"
    },
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQAAsDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABAX/xAAfEAACAgICAwEAAAAAAAAAAAABAgMRAAQhQQUSUXH/xAAVAQEBAAAAAAAAAAAAAAAAAAABAv/EABcRAQEBAQAAAAAAAAAAAAAAAAEAEUH/2gAMAwEAAhEDEQA/AKvlNt9RIjGQtuASQK/MbrTJs68cyClkUMB8yXtze0zR1E6jmnF03RxGu6xwIiigBwB1ldhcL//Z"
  },
  "heroScene": {
    "src": "/photos/hero-church.jpg",
    "width": 828,
    "height": 1104,
    "alt": {
      "en": "Inside the church",
      "ml": "പള്ളിക്കകം"
    },
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQAAwDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAQIDBf/EACAQAAIBAwQDAAAAAAAAAAAAAAECAwAEEQUSITEVQUL/xAAVAQEBAAAAAAAAAAAAAAAAAAACA//EABYRAQEBAAAAAAAAAAAAAAAAAAEAEf/aAAwDAQACEQMRAD8AhHZON6wqWVOSSexTeLiYAu2GPYoWDTzWEkkYIkQAgN9g+qzrjU5ElwUfBAIwxHFRBnpf/9k="
  }
};
