import type { Localized } from "./types";

/** Interface strings (buttons, labels, section titles). */
export const ui = {
  tapToOpen: { en: "Tap to open", ml: "തുറക്കാൻ തൊടുക" },
  youAreInvited: { en: "You Are Invited", ml: "നിങ്ങളെ ക്ഷണിക്കുന്നു" },
  and: { en: "and", ml: "&" },
  dear: { en: "Dear", ml: "പ്രിയപ്പെട്ട" },
  dearGuest: { en: "Dear Guest", ml: "പ്രിയ അതിഥി" },
  musicOn: { en: "Music on", ml: "സംഗീതം ഓൺ" },
  musicOff: { en: "Music off", ml: "സംഗീതം ഓഫ്" },
  switchLanguage: { en: "Switch language", ml: "ഭാഷ മാറ്റുക" },
  otherLanguage: { en: "മലയാളം", ml: "English" },
  directions: { en: "Directions", ml: "വഴി കാണിക്കുക" },
  addToCalendar: { en: "Add to calendar", ml: "കലണ്ടറിൽ ചേർക്കുക" },
  googleCalendar: { en: "Google Calendar", ml: "ഗൂഗിൾ കലണ്ടർ" },
  appleCalendar: { en: "Apple / Outlook (.ics)", ml: "ആപ്പിൾ / ഔട്ട്‌ലുക്ക് (.ics)" },
  dressCode: { en: "Dress code", ml: "വേഷവിധാനം" },
  celebrationLead: { en: "An evening of joy, one sacred promise.", ml: "ആഹ്ലാദത്തിന്റെ ഒരു സായാഹ്നം, ഒരു പവിത്ര വാഗ്ദാനം." },
  celebration: { en: "The celebration", ml: "ആഘോഷം" },
  countdownLead: { en: "Counting the days to the ceremony", ml: "ചടങ്ങിലേക്ക് ഇനി" },
  days: { en: "days", ml: "ദിവസം" },
  hours: { en: "hours", ml: "മണിക്കൂർ" },
  minutes: { en: "minutes", ml: "മിനിറ്റ്" },
  seconds: { en: "seconds", ml: "സെക്കൻഡ്" },
  engaged: { en: "Engaged!", ml: "വിവാഹനിശ്ചയം കഴിഞ്ഞു!" },
  scratchToReveal: { en: "Scratch to reveal", ml: "ചുരണ്ടി നോക്കൂ" },
  coupleLead: { en: "Two hearts, one calling.", ml: "രണ്ടു ഹൃദയങ്ങൾ, ഒരേ വിളി." },
  theGroom: { en: "The groom-to-be", ml: "വരൻ" },
  theBride: { en: "The bride-to-be", ml: "വധു" },
  livestreamLead: { en: "Can't be there in person?", ml: "നേരിട്ട് എത്താൻ കഴിയുന്നില്ലേ?" },
  livestream: { en: "Watch live", ml: "തത്സമയം കാണുക" },
  blessingsTitle: { en: "With love", ml: "സ്നേഹപൂർവ്വം" },
} satisfies Record<string, Localized>;
