// Generates src/content/photos.generated.ts (dimensions, blur placeholders and alt text) from /public/photos.
// Usage: npm run photos
import sharp from "sharp";
import { writeFile } from "node:fs/promises";
import path from "node:path";

const dir = path.resolve("public/photos");

async function describe(file, alt) {
  const abs = path.join(dir, file);
  const meta = await sharp(abs).metadata();
  const blur = await sharp(abs).resize(16, 16, { fit: "inside" }).jpeg({ quality: 40 }).toBuffer();
  return { src: `/photos/${file}`, width: meta.width, height: meta.height, alt, blurDataURL: `data:image/jpeg;base64,${blur.toString("base64")}` };
}

const hero = await describe("hero.jpg", { en: "Tosmy and Priyank", ml: "ടോസ്മിയും പ്രിയങ്കും", kn: "ಟೋಸ್ಮಿ ಮತ್ತು ಪ್ರಿಯಾಂಕ್" });
const heroCouple = await describe("hero-couple.jpg", { en: "Tosmy and Priyank", ml: "ടോസ്മിയും പ്രിയങ്കും", kn: "ಟೋಸ್ಮಿ ಮತ್ತು ಪ್ರಿಯಾಂಕ್" });
const heroScene = await describe("hero-church.jpg", { en: "Inside the church", ml: "പള്ളിക്കകം", kn: "ಚರ್ಚ್‌ನ ಒಳಗೆ" });

const out = `// AUTO-GENERATED by scripts/photos.mjs — do not edit by hand.
import type { Photo } from "./types";

export const photos: { hero: Photo; heroCouple: Photo; heroScene: Photo } = ${JSON.stringify({ hero, heroCouple, heroScene }, null, 2)};
`;
await writeFile(path.resolve("src/content/photos.generated.ts"), out);
console.log("photos.generated.ts written: hero, heroCouple, heroScene");
